version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: invalytics_db
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env

volumes:
  pg_data: